name: Run clang-format
on: [pull_request]

jobs:
  pre-ci:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Clang Format
        run: |
          /bin/bash ./ci_docker/clang_format_check.sh
      - name: build
        run: |
          /bin/bash ./ci_docker/build.sh
      - name: test
        run: |
          /bin/bash ./ci_docker/run_test.sh

